---
permalink: tenant/what-platform-services-are.html 
sidebar: sidebar 
keywords: platform services 
summary: StorageGRID 平台服务允许您向外部目标发送事件通知以及S3对象和对象元数据的副本、从而帮助您实施混合云战略。 
---
= 管理平台服务：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
StorageGRID 平台服务允许您向外部目标发送事件通知以及S3对象和对象元数据的副本、从而帮助您实施混合云战略。

如果您的租户帐户允许使用平台服务，则可以为任何 S3 存储分段配置以下服务：

CloudMirror 复制:: 使用 ... link:understanding-cloudmirror-replication-service.html["StorageGRID CloudMirror 复制服务"] 将特定对象从StorageGRID 存储分段镜像到指定的外部目标。
+
--
例如，您可以使用 CloudMirror 复制将特定客户记录镜像到 Amazon S3 ，然后利用 AWS 服务对数据执行分析。


NOTE: 如果源存储分段启用了 S3 对象锁定，则不支持 CloudMirror 复制。

--
通知:: 使用 ... link:understanding-notifications-for-buckets.html["每个存储分段的事件通知"] 将有关对对象执行的特定操作的通知发送到指定的外部Amazon Simple Notification Service (Amazon SNS)。
+
--
例如，您可以配置向管理员发送有关添加到存储分段中的每个对象的警报，这些对象表示与关键系统事件关联的日志文件。


NOTE: 虽然可以在启用了 S3 对象锁定的存储分段上配置事件通知，但通知消息中不会包含对象的 S3 对象锁定元数据（包括保留至日期和合法保留状态）。

--
搜索集成服务:: 使用 link:understanding-search-integration-service.html["搜索集成服务"] 将S3对象元数据发送到可使用外部服务在其中搜索或分析元数据的指定El路径 搜索索引。
+
--
例如，您可以将存储分段配置为将 S3 对象元数据发送到远程 Elasticsearch 服务。然后，您可以使用 Elasticsearch 跨存储分段执行搜索，并对对象元数据中存在的模式执行复杂的分析。


NOTE: 虽然可以在启用了 S3 对象锁定的情况下在存储分段上配置 Elasticsearch 集成，但通知消息中不会包含对象的 S3 对象锁定元数据（包括保留截止日期和合法保留状态）。

--


由于平台服务的目标位置通常不在 StorageGRID 部署中，因此平台服务可以为您提供使用外部存储资源，通知服务以及数据搜索或分析服务所带来的强大功能和灵活性。

可以为一个 S3 存储分段配置任何平台服务组合。例如，您可以在 StorageGRID S3 存储分段上配置 CloudMirror 服务和通知，以便将特定对象镜像到 Amazon Simple Storage Service ，同时向第三方监控应用程序发送有关每个此类对象的通知，以帮助您跟踪 AWS 支出。


TIP: StorageGRID 管理员必须使用网格管理器或网格管理 API 为每个租户帐户启用平台服务。



== 如何配置平台服务

平台服务可与您使用配置的外部端点进行通信 link:configuring-platform-services-endpoints.html["租户管理器"] 或 link:understanding-tenant-management-api.html["租户管理 API"]。每个端点表示一个外部目标、例如StorageGRID S3存储分段、Amazon Web Services存储分段、Amazon SNS主题或本地、AWS或其他位置托管的ElanicSearch集群。

创建外部端点后、您可以通过向存储分段添加XML配置来为该存储分段启用平台服务。XML 配置可确定存储分段应处理的对象，存储分段应执行的操作以及存储分段应用于服务的端点。

您必须为要配置的每个平台服务添加单独的 XML 配置。例如：

* 所需的所有对象的密钥均以开头 `/images` 要复制到Amazon S3存储分段、您必须向源存储分段添加复制配置。
* 如果您还希望在这些对象存储到存储分段时发送通知，则必须添加通知配置。
* 最后，如果要为这些对象的元数据编制索引，则必须添加用于实施搜索集成的元数据通知配置。


配置 XML 的格式由用于实施 StorageGRID 平台服务的 S3 REST API 控制：

[cols="1a,2a,1a"]
|===
| 平台服务 | S3 REST API | 请参见 


 a| 
CloudMirror 复制
 a| 
* GetBucketReplication
* PutBucketReplication

 a| 
* link:configuring-cloudmirror-replication.html["CloudMirror 复制"]
* link:../s3/operations-on-buckets.htmll["对存储分段执行的操作"]




 a| 
通知
 a| 
* GetBucketNotizationConfiguration
* PutBucketNotizationConfiguration

 a| 
* link:configuring-event-notifications.html["通知"]
* link:../s3/s3/operations-on-buckets.html["对存储分段执行的操作"]




 a| 
搜索集成
 a| 
* 获取存储分段元数据通知配置
* PUT 存储分段元数据通知配置

 a| 
* link:using-search-integration-service.html["搜索集成"]
* link:../s3/custom-operations-on-buckets.html["StorageGRID自定义操作"]


|===
.相关信息
link:considerations-for-platform-services.html["平台服务注意事项"]
