---
permalink: admin/archive-node-configuration-and-operation.html 
sidebar: sidebar 
keywords: archive node configuration 
summary: 您的 StorageGRID 系统会将归档节点作为一个位置来管理，在该位置，对象会无限期地存储，并且始终可以访问。 
---
= 归档节点配置和操作
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您的 StorageGRID 系统会将归档节点作为一个位置来管理，在该位置，对象会无限期地存储，并且始终可以访问。

在读取对象后、系统会根据为StorageGRID系统定义的信息生命周期管理(ILM)规则、将副本复制到所有必需位置、包括归档节点。归档节点充当 TSM 服务器的客户端， TSM 客户端库通过 StorageGRID 软件安装过程安装在归档节点上。定向到归档节点进行存储的对象数据会在收到时直接保存到 TSM 服务器。归档节点不会在将对象数据保存到 TSM 服务器之前暂存对象数据，也不会执行对象聚合。但是，如果数据速率需要，归档节点可以在一个事务中向 TSM 服务器提交多个副本。

在归档节点将对象数据保存到 TSM 服务器后， TSM 服务器将使用其生命周期 / 保留策略来管理对象数据。必须定义这些保留策略，使其与归档节点的操作兼容。也就是说，归档节点保存的对象数据必须无限期存储，并且必须始终可由归档节点访问，除非归档节点将其删除。

StorageGRID 系统的 ILM 规则与 TSM 服务器的生命周期 / 保留策略之间没有连接。每个对象彼此独立运行；但是，在将每个对象载入 StorageGRID 系统时，您可以为其分配一个 TSM 管理类。此管理类将与对象数据一起传递到 TSM 服务器。通过将不同的管理类分配给不同的对象类型，您可以将 TSM 服务器配置为将对象数据放置在不同的存储池中，或者根据需要应用不同的迁移或保留策略。例如，标识为数据库备份的对象（临时内容，不能使用较新的数据覆盖）的处理方式可能与应用程序数据（必须无限期保留的固定内容）不同。

归档节点可以与新的或现有的 TSM 服务器集成；它不需要专用的 TSM 服务器。TSM 服务器可以与其他客户端共享，但前提是 TSM 服务器的大小应适合最大预期负载。TSM 必须安装在与归档节点不同的服务器或虚拟机上。

可以将多个归档节点配置为写入同一个 TSM 服务器；但是，只有当归档节点向 TSM 服务器写入不同的数据集时，才建议使用此配置。当每个归档节点向归档写入相同对象数据的副本时，建议不要将多个归档节点配置为写入同一 TSM 服务器。在后一种情况下，对于对象数据的独立冗余副本，这两个副本都会发生单点故障（ TSM 服务器）。

归档节点不使用TSM的分层存储管理(HSM)组件。
