---
permalink: admin/configuring-audit-client-access.html 
sidebar: sidebar 
keywords: audit client, ams, audit management service 
summary: 管理节点通过审核管理系统（ Audit Management System ， AMS ）服务将所有审核的系统事件记录到可通过审核共享访问的日志文件中，该文件会在安装时添加到每个管理节点中。审核共享会自动启用为只读共享。 
---
= 配置NFS的审核客户端访问
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理节点通过审核管理系统（ Audit Management System ， AMS ）服务将所有审核的系统事件记录到可通过审核共享访问的日志文件中，该文件会在安装时添加到每个管理节点中。审核共享会自动启用为只读共享。


NOTE: 对NFS的支持已弃用、将在未来版本中删除。

要访问审核日志、您可以配置客户端对NFS审核共享的访问权限。或者、您也可以 link:../monitor/considerations-for-external-syslog-server.html["使用外部系统日志服务器"]。

StorageGRID 系统会使用肯定确认来防止在将审核消息写入日志文件之前丢失这些消息。消息会一直在服务中排队，直到 AMS 服务或中间审核中继服务确认对其进行控制为止。有关详细信息，请参见 link:../audit/index.html["查看审核日志"]。

.开始之前
* 您拥有 `Passwords.txt` 具有root/admin密码的文件。
* 您拥有 `Configuration.txt` 文件(在恢复软件包中提供)。
* 审核客户端正在使用 NFS 版本 3 （ NFSv3 ）。


.关于此任务
对 StorageGRID 部署中要从中检索审核消息的每个管理节点执行此操作步骤 。

.步骤
. 登录到主管理节点：
+
.. 输入以下命令： `ssh admin@_primary_Admin_Node_IP_`
.. 输入中列出的密码 `Passwords.txt` 文件
.. 输入以下命令切换到root： `su -`
.. 输入中列出的密码 `Passwords.txt` 文件
+
以root用户身份登录后、提示符将从变为 `$` to `#`。



. 确认所有服务的状态均为正在运行或已验证。输入 ... `storagegrid-status`
+
如果任何服务未列为"正在运行"或"已验证"、请先解决问题、然后再继续。

. 返回到命令行。按 * 。 Ctrl+* 。
. 启动 NFS 配置实用程序。输入 ... `config_nfs.rb`
+
[listing]
----

-----------------------------------------------------------------
| Shares               | Clients              | Config          |
-----------------------------------------------------------------
| add-audit-share      | add-ip-to-share      | validate-config |
| enable-disable-share | remove-ip-from-share | refresh-config  |
|                      |                      | help            |
|                      |                      | exit            |
-----------------------------------------------------------------
----
. 添加审核客户端： `add-audit-share`
+
.. 出现提示时、输入审核客户端的审核共享IP地址或IP地址范围： `client_IP_address`
.. 出现提示时，按 * 输入 * 。


. 如果允许多个审核客户端访问审核共享、请添加其他用户的IP地址： `add-ip-to-share`
+
.. 输入审核共享的编号： `_audit_share_number_`
.. 出现提示时、输入审核客户端的审核共享IP地址或IP地址范围： `_client_IP_address_`
.. 出现提示时，按 * 输入 * 。
+
此时将显示 NFS 配置实用程序。

.. 对有权访问审核共享的其他每个审核客户端重复这些子步骤。


. （可选）验证您的配置。
+
.. 输入以下内容： `validate-config`
+
此时将检查并显示这些服务。

.. 出现提示时，按 * 输入 * 。
+
此时将显示 NFS 配置实用程序。

.. 关闭NFS配置实用程序： `exit`


. 确定是否必须在其他站点启用审核共享。
+
** 如果 StorageGRID 部署是单个站点，请转至下一步。
** 如果 StorageGRID 部署包括其他站点的管理节点，请根据需要启用这些审核共享：
+
... 远程登录到站点的管理节点：
+
.... 输入以下命令： `ssh admin@_grid_node_IP_`
.... 输入中列出的密码 `Passwords.txt` 文件
.... 输入以下命令切换到root： `su -`
.... 输入中列出的密码 `Passwords.txt` 文件


... 重复上述步骤为每个附加管理节点配置审核共享。
... 关闭远程安全 Shell 登录到远程管理节点。输入 ... `exit`




. 从命令Shell中注销： `exit`
+
NFS 审核客户端将根据其 IP 地址获得对审核共享的访问权限。通过将新 NFS 审核客户端的 IP 地址添加到共享中来向该客户端授予对审核共享的访问权限，或者通过删除现有审核客户端的 IP 地址来删除该客户端。


