---
permalink: admin/managing-tenants.html 
sidebar: sidebar 
keywords: manage tenants, tenant account, what is a tenant 
summary: 作为网格管理员、您可以创建和管理S3和Swift客户端用于存储和检索对象的租户帐户。 
---
= 管理租户：概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
作为网格管理员、您可以创建和管理S3和Swift客户端用于存储和检索对象的租户帐户。


NOTE: 对Swift客户端应用程序的支持已弃用、将在未来版本中删除。



== 什么是租户帐户？

租户帐户允许您使用简单存储服务（ S3 ） REST API 或 Swift REST API 在 StorageGRID 系统中存储和检索对象。

每个租户帐户都具有联合组或本地组、用户、S3分段或Swift容器以及对象。

租户帐户可用于按不同实体隔离存储的对象。例如，以下任一使用情形均可使用多个租户帐户：

* * 企业用例： * 如果您在企业应用程序中管理 StorageGRID 系统，则可能需要按组织中的不同部门隔离网格的对象存储。在这种情况下，您可以为营销部门，客户支持部门，人力资源部门等创建租户帐户。
+

NOTE: 如果使用S3客户端协议、则可以使用S3分段和分段策略在企业的各个部门之间隔离对象。您不需要使用租户帐户。请参见实施说明 link:../s3/bucket-and-group-access-policies.html["S3存储分段和存储分段策略"] 有关详细信息 ...

* * 服务提供商用例： * 如果您将 StorageGRID 系统作为服务提供商进行管理，则可以按要在网格上租用存储的不同实体来隔离网格的对象存储。在这种情况下，您将为公司 A ，公司 B ，公司 C 等创建租户帐户。


有关详细信息，请参见 link:../tenant/index.html["使用租户帐户"]。



== 如何创建租户帐户？

创建租户帐户时，您可以指定以下信息：

* 基本信息、包括租户名称、客户端类型(S3或Swift)和可选存储配额。
* 租户帐户的权限、例如租户帐户是否可以使用S3平台服务、配置自己的身份源、使用S3 Select或使用网格联盟连接。
* 租户的初始root访问权限、具体取决于StorageGRID 系统是使用本地组和用户、身份联合还是单点登录(SSO)。


此外、如果S3租户帐户需要符合法规要求、您可以为StorageGRID 系统启用S3对象锁定设置。启用 S3 对象锁定后，所有 S3 租户帐户均可创建和管理合规的存储分段。



== 租户管理器的用途是什么？

创建租户帐户后、租户用户可以登录到租户管理器来执行如下任务：

* 设置身份联合(除非身份源与网格共享)
* 管理组和用户
* 使用网格联盟进行帐户克隆和跨网格复制
* 管理 S3 访问密钥
* 创建和管理S3存储分段
* 使用S3平台服务
* 使用 S3 Select
* 监控存储使用情况



TIP: 虽然S3租户用户可以使用租户管理器创建和管理S3访问密钥和存储分段、但他们必须使用S3客户端应用程序来加存和管理对象。请参见 link:../s3/index.html["使用S3 REST API"] 了解详细信息。


TIP: Swift 用户必须具有 root 访问权限才能访问租户管理器。但是， " 根 " 访问权限不允许用户通过 Swift REST API 的身份验证来创建容器和载入对象。用户必须具有 Swift 管理员权限才能向 Swift REST API 进行身份验证。
