---
permalink: admin/migrating-objects-from-cloud-tiering-s3-to-cloud-storage-pool.html 
sidebar: sidebar 
keywords: cloud tiering 
summary: 如果您当前正在使用Cloud Tiering - Simple Storage Service功能将对象数据分层到S3存储分段、则应将对象迁移到云存储池。云存储池提供了一种可扩展的方法，可利用 StorageGRID 系统中的所有存储节点。 
---
= 将对象从 Cloud Tiering - S3 迁移到云存储池
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您当前正在使用*云分层-简单存储服务(S3)*功能将对象数据分层到S3存储分段，则应将对象迁移到云存储池。云存储池提供了一种可扩展的方法，可利用 StorageGRID 系统中的所有存储节点。

.开始之前
* 您将使用登录到网格管理器 link:../admin/web-browser-requirements.html["支持的 Web 浏览器"]。
* 您已拥有 link:admin-group-permissions.html["特定访问权限"]。
* 您已将对象存储在为 Cloud Tiering 配置的 S3 存储分段中。



NOTE: 迁移对象数据之前，请联系您的 NetApp 客户代表，了解并管理任何相关成本。

.关于此任务
从 ILM 角度来看，云存储池与存储池类似。但是，虽然存储池包含 StorageGRID 系统中的存储节点或归档节点，但云存储池包含一个外部 S3 存储分段。

在将对象从 Cloud Tiering - S3 迁移到云存储池之前，必须先创建 S3 存储分段，然后在 StorageGRID 中创建云存储池。然后，您可以创建一个新的 ILM 策略，并将用于存储 Cloud Tiering 分段中对象的 ILM 规则替换为在 Cloud Storage Pool 中存储相同对象的克隆 ILM 规则。


NOTE: 当对象存储在云存储池中时、这些对象的副本不能同时存储在StorageGRID 中。如果您当前用于云分层的 ILM 规则配置为同时将对象存储在多个位置，请考虑是否仍要执行此可选迁移，因为您将丢失此功能。如果继续执行此迁移，则必须创建新规则，而不是克隆现有规则。

.步骤
. 创建云存储池。
+
为云存储池使用新的 S3 存储分段，以确保其仅包含由云存储池管理的数据。

. 在活动ILM策略中找到要存储在云层分段中的发生原因对象的任何ILM规则。
. 克隆上述每个规则。
. 在克隆的规则中，将放置位置更改为新的云存储池。
. 保存克隆的规则。
. 创建使用新规则的新策略。
. 模拟并激活新策略。
+
激活新策略并进行 ILM 评估后，对象将从为 Cloud Tiering 配置的 S3 存储分段移动到为 Cloud Storage Pool 配置的 S3 存储分段。网格上的可用空间不受影响。将对象移至云存储池后，这些对象将从 Cloud Tiering 分段中删除。



.相关信息
link:../ilm/index.html["使用 ILM 管理对象"]
