---
permalink: admin/storage-node-configuration-settings.html 
sidebar: sidebar 
keywords: storage node, configuration settings, counters 
summary: 每个存储节点都使用多个配置设置和计数器。要清除警报，您可能需要查看当前设置或重置计数器 \ （原有系统 \ ）。 
---
= 存储节点配置设置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每个存储节点都使用多个配置设置和计数器。您可能需要查看当前设置或重置计数器才能清除警报（旧系统）。


CAUTION: 除非文档中有明确说明，否则在修改任何存储节点配置设置之前，应咨询技术支持。您可以根据需要重置事件计数器以清除原有警报。

按照以下步骤访问存储节点的配置设置和计数器。

.步骤
. 选择 * 支持 * > * 工具 * > * 网格拓扑 * 。
. 选择 * 站点 _* > * 存储节点 _* 。
. 展开存储节点并选择服务或组件。
. 选择 * 配置 * 选项卡。


下表汇总了存储节点配置设置。



== LDR

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
HTTP 状态
 a| 
HSTE
 a| 
用于S3、Swift和其他内部StorageGRID 流量的HTTP的当前状态：

* 脱机：不允许执行任何操作，任何尝试打开与 LDR 服务的 HTTP 会话的客户端应用程序都会收到错误消息。活动会话正常关闭。
* 联机：操作继续正常




 a| 
自动启动 HTTP
 a| 
HTA
 a| 
* 如果选择此选项，则重新启动时系统的状态取决于 * LDR* > * 存储 * 组件的状态。如果重新启动时 * LDR* > * 存储 * 组件为只读，则 HTTP 接口也为只读。如果 * LDR* > * 存储 * 组件为联机，则 HTTP 也为联机。否则， HTTP 接口将保持脱机状态。
* 如果未选中，则 HTTP 接口将保持脱机状态，直到显式启用为止。


|===


== LDR > 数据存储

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
重置丢失的对象计数
 a| 
RCOR
 a| 
重置此服务中丢失的对象数量的计数器。

|===


== LDR > 存储

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
存储状态—所需
 a| 
SSD
 a| 
用户可配置的存储组件所需状态设置。LDR 服务将读取此值并尝试与此属性指示的状态匹配。此值在重新启动后保持不变。

例如，您可以使用此设置强制存储成为只读存储，即使有足够的可用存储空间也是如此。这对于故障排除非常有用。

属性可以采用以下值之一：

* 脱机：当所需状态为脱机时， LDR 服务会使 * LDR* > * 存储 * 组件脱机。
* 只读：如果所需状态为只读、LDR服务会将存储状态更改为只读、并停止接受新内容。但是、LDR服务仍会接受S3或ILM驱动的清除和删除请求。请注意，内容可能会继续短时间保存到存储节点中，直到打开的会话关闭为止。
* 联机：在正常系统操作期间，将此值保留为联机。存储状态—存储组件的当前状态将由服务根据 LDR 服务的状况（例如可用对象存储空间量）动态设置。如果空间不足，则组件将变为只读。




 a| 
运行状况检查超时
 a| 
SHCT
 a| 
运行状况检查测试必须完成才能将存储卷视为运行状况良好的时间限制（以秒为单位）。只有在支持部门要求更改此值时，才更改此值。

|===


== LDR > 验证

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
重置缺少的对象计数
 a| 
VNMI
 a| 
重置检测到的缺失对象数（ Oomis ）。请仅在对象存在检查完成后使用。StorageGRID 系统会自动还原缺少的复制对象数据。



 a| 
验证率
 a| 
VPRI.
 a| 
设置进行后台验证的速率。请参见有关配置后台验证速率的信息。



 a| 
重置损坏对象计数
 a| 
VCCR
 a| 
重置在后台验证期间发现的已复制对象数据损坏的计数器。此选项可用于清除检测到损坏的对象（ OCOR ）警报条件。



 a| 
删除隔离的对象
 a| 
OQRT
 a| 
从隔离目录中删除损坏的对象，将隔离对象的计数重置为零，然后清除检测到的隔离对象（ OQRT ）警报。在 StorageGRID 系统自动还原损坏的对象后，将使用此选项。

如果触发对象丢失警报，技术支持可能希望访问隔离的对象。在某些情况下，隔离的对象对于数据恢复或调试导致对象副本损坏的底层问题可能很有用。

|===


== LDR > 擦除编码

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
重置写入失败计数
 a| 
RSWF
 a| 
将擦除编码对象数据写入失败时的计数器重置到存储节点。



 a| 
重置读取失败计数
 a| 
RSRF
 a| 
重置从存储节点读取经过纠删编码的对象数据失败的计数器。



 a| 
重置删除失败计数
 a| 
RSDF
 a| 
重置从存储节点删除经过纠删编码的对象数据失败的计数器。



 a| 
重置检测到的损坏副本计数
 a| 
RSCC
 a| 
重置存储节点上经过纠删编码的对象数据的损坏副本数计数器。



 a| 
重置检测到的损坏片段计数
 a| 
RSCD
 a| 
重置存储节点上擦除编码对象数据损坏片段的计数器。



 a| 
重置检测到的缺失片段计数
 a| 
R贴 片式
 a| 
重置存储节点上缺少纠删编码对象数据片段的计数器。请仅在对象存在检查完成后使用。

|===


== LDR > 复制

[cols="2a,1a,3a"]
|===
| 属性名称 | 代码 | Description 


 a| 
重置入站复制失败计数
 a| 
RICR
 a| 
重置入站复制失败的计数器。此操作可用于清除 RIRF （入站复制 - 失败）警报。



 a| 
重置出站复制失败计数
 a| 
ROCR
 a| 
重置出站复制失败的计数器。此操作可用于清除 RORF （出站复制 - 失败）警报。



 a| 
禁用入站复制
 a| 
DSIR
 a| 
选择此项可在维护或测试操作步骤 过程中禁用入站复制。在正常操作期间保持未选中状态。

禁用入站复制后、可以从存储节点中检索对象以复制到StorageGRID 系统中的其他位置、但无法从其他位置将对象复制到此存储节点：LDR服务为只读。



 a| 
禁用出站复制
 a| 
DSOR
 a| 
选择此选项可在维护或测试操作步骤 过程中禁用出站复制（包括 HTTP 检索的内容请求）。在正常操作期间保持未选中状态。

禁用出站复制后、可以将对象复制到此存储节点、但无法从此存储节点检索对象以复制到StorageGRID 系统中的其他位置。LDR 服务为只写服务。

|===