---
permalink: maintain/accessing-server-manager-log-file.html 
sidebar: sidebar 
keywords: storagegrid, server manager, log file 
summary: 如果使用 Server Manager 时出现问题，请检查其日志文件。 
---
= 对 Server Manager 进行故障排除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果使用 Server Manager 时出现问题，请检查其日志文件。

与Server Manager相关的错误消息会记录在Server Manager日志文件中、该文件位于： `/var/local/log/servermanager.log`

检查此文件中有关故障的错误消息。如果需要，请将问题描述 升级到技术支持。系统可能会要求您将日志文件转发给技术支持。



== 存在错误状态的服务

如果您检测到某个服务已进入错误状态，请尝试重新启动此服务。

.开始之前
您拥有 `Passwords.txt` 文件

.关于此任务
Server Manager 可监控服务并重新启动任何意外停止的服务。如果服务失败， Server Manager 将尝试重新启动它。如果在五分钟内启动服务的尝试失败三次，则该服务将进入错误状态。Server Manager 不会尝试再次重新启动。

.步骤
. 登录到网格节点：
+
.. 输入以下命令： `ssh admin@_grid_node_IP_`
.. 输入中列出的密码 `Passwords.txt` 文件
.. 输入以下命令切换到root： `su -`
.. 输入中列出的密码 `Passwords.txt` 文件


+
以root用户身份登录后、提示符将从变为 `$` to `#`。

. 确认服务的错误状态： `service _servicename_ status`
+
例如：

+
[listing]
----
service ldr status
----
+
如果服务处于错误状态、则会返回以下消息： `_servicename_ in error state`。例如：

+
[listing]
----
ldr in error state
----
+

NOTE: 服务状态为 `disabled`请参见的说明 link:using-donotstart-file.html["删除服务的 DoNotStart 文件"]。

. 尝试通过重新启动服务来删除错误状态： `service _servicename_ restart`
+
如果服务无法重新启动，请联系技术支持。

. 从命令Shell中注销： `exit`

